---
# vi: set ft=ansible :

- name: Deploy password file
  copy:
    dest: '/var/lib/restic/passwd_{{ item.name }}'
    content: '{{ item.password }}'
    mode: '0600'
    owner: '{{ restic_user }}'
    group: '{{ restic_group }}'
  no_log: true
  ignore_errors: true

- name: Deploy cron script
  template:
    src: 'restic.cron.j2'
    dest: '/etc/cron.d/restic-{{ item.name }}'
    mode: '0644'
