---

driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: yamllint.yml
verifier:
  name: testinfra
  lint:
    name: flake8
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default

platforms:
  - name: xenial64
    box: ubuntu/xenial64
    memory: 512
    cpus: 1
